services:

 ansible:
  build:
   args:
    - IMAGE=${IMAGE}
    - VERSION=${VERSION}
   context: .
   dockerfile: ${DOCKERFILE}
  container_name: ${NAME}
  environment:
   - CRON=${CRON}
   - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
   - STREAMING_HOST=${STREAMING_HOST}
   - STREAMING_PORT=${STREAMING_PORT}
   - SMTP_USERNAME=${SMTP_USERNAME}
   - SMTP_PASSWORD=${SMTP_PASSWORD}
   - SMTP_PORT=${SMTP_PORT}
   - SMTP_SERVER=${SMTP_SERVER}
   - STREAMING_HOST=${STREAMING_HOST}
   - TZ=${TZ}
  image: ${IMAGE_LOCAL}/${NAME}:${VERSION}
  restart: ${RESTART}
